### ISSUE TITLE
Possible with a CCGX

### ISSUE THREAD

**Issue by gharshaw** [kwindrem/ExtTransferSwitch#1]
Can this functionality be used on a CCGX?  I currently have a relay that is energized with 12v when my transfer switch transfers to generator. I monitor this for auto starting the generator when the AC calls for cooling and we have lost grid power. A pet safety function when we are away from the coach.

**Comment by kwindrem** [comment]
Unfortunately, the CCGX does not have any digital inputs so no this won't work. Sorry.

**Comment by gharshaw** [comment]
I didn't think so but I thought I'd ask anyway

Thank you
