### ISSUE TITLE
Is an  Optocoupler needed

### ISSUE THREAD

**Issue by gharshaw** [kwindrem/ExtTransferSwitch#12]
@kwindrem , I'd like to get your opinion on the wiring setup with my transfer switch. My transfer switch has isolated relays that close when the generator is on or shore power is off. I was thinking about just using that relay direct to the digital input. The transfer switch is about 5 feet from the Cerbo. Any EMF concerns? Is this method okay or should I use an optocoupler energized with 12v via the transfer switch relay . 
I appreciate your thoughts on this
Gene

**Comment by kwindrem** [comment]
If your transfer switch has an isolated pole, then yes, it can be wired directly to the GX device's digital inputs.

If the contacts close when on generator, then the standard polarity will be fine. If the contacts close when on shore power, then you would need to invert the polarity in the External TS device setup in the GX device.

If you don't have an extra pole on the relay, you could use a second relay with its coil in parallel with the existing one.

**Comment by gharshaw** [comment]
Thank you!
