### ISSUE TITLE
No FileSets v3.20-45

### ISSUE THREAD

**Issue by drtinaz** [kwindrem/ExtTransferSwitch#14]
No FileSets v3.20-45

**Comment by kwindrem** [comment]
ExtTransferSwitch is being merged into GuiMods due to all the overlap in modified files.

**Comment by drtinaz** [comment]
What version of guimods will include the merge? Or is this something still in the days to come?

**Comment by kwindrem** [comment]
It will be v10.0. I need to do some more testing but am hoping to release later today. If not, early tomorrow (pacific time).

**Comment by kwindrem** [comment]
ExtTransferSwitch functionality moved to GuiMods
package is obsolete as of v3.20~45
no further updates - support ends immediately
