### ISSUE TITLE
Ability to set via ModBus or some other way via TCP?

### ISSUE THREAD

**Issue by zorrobyte** [kwindrem/ExtTransferSwitch#2]
I'm running home assistant and managing when my generator start/stops via Victron (SoC and manual start) and Node Red. This means I know when the generator is running without needing to install a relay on the transfer switch as suggested for the digitalinput for this mod.

I was considering deploying an ESP32 and using a pin for the digital input (to the GX), but this feels pretty hacky.

I also write software, so I could implement something myself, if I get started. But on initial pass, do you know if any way to edit/add modbus registers without having to modify the core victron OS?

**Comment by kwindrem** [comment]
Sorry, I don't know anything about modbus.

Currently, my code looks for a digital input programmed as the transfer switch input before doing anything else. It also uses the state of that input for it's logic. You could modify the code to create a dbus parameter that could then be accessed from the outside world once you figure out how to access things from modbus, or other ways in.

Note that basing the transfer switch state on generator running/stopped state might not be the best. The generator could be running but not supplying the load to the Multi.

**Comment by zorrobyte** [comment]
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/7257172/210277077-29bf5f04-9ffb-4be1-b468-53edd39b4f2a.png">

>Note that basing the transfer switch state on generator running/stopped state might not be the best. The generator could be running but not supplying the load to the Multi.

Good idea! I got so far as to check for the generator light being on and seeing if there is voltage at L1 input. There's no guarantee that the multiplus will kick over though, and I need to check for that also.

Looking through your code, it's python, glorious python! I'll fork and work on an externally controllable solution. 

Thanks for getting me started!

**Comment by zorrobyte** [comment]
For anyone else running across this, just wire a relay to a digital input!
<img width="828" alt="image" src="https://user-images.githubusercontent.com/7257172/210287670-50dea2b1-d7b1-4717-841e-f5811f6285a1.png">

Then you can use node red on device, or via d-bus, mqtt to set generator state!
