### ISSUE TITLE
No ExtTransferSwitch in Package Manager

### ISSUE THREAD

**Issue by Lowbank** [kwindrem/ExtTransferSwitch#3]
Hi kwindrm 
I am new to this but I can not find ExtTransferSwitch in the Package Manager am I missing somthing ?
![Image](https://user-images.githubusercontent.com/13149096/234605951-2afa680e-ff4c-43b2-94fc-8e1afa7970cd.png)
![Image](https://user-images.githubusercontent.com/13149096/234605979-dc888beb-917b-4a65-9a03-6d9ebb1fd5dc.png)
![Image](https://user-images.githubusercontent.com/13149096/234606645-796829ab-4f0c-4bb1-8763-47d5ba189965.png)
Cheers Jon

**Comment by kwindrem** [comment]
It looks like I did not add ExtTransferSwitch to the default packages. I’ll fix that but for now you can add it from “new” in the Inactive packages list.name: ExtTransferSwitchGitHub user: kwindremBranch: latest--KevinOn Apr 26, 2023, at 7:25 AM, Lowbank ***@***.***> wrote:﻿
Hi kwindrm
I am new to this but I can not find ExtTransferSwitch in the Package Manager am I missing somthing ?



Cheers Jon

**Comment by Lowbank** [comment]
Hi Kevin
Thanks for reply and info making baby steps. Package manager not dowloading packages? have had no problem with GuiMods.
using a Gerbo V2.94
Cheers Jon
![Image](https://user-images.githubusercontent.com/13149096/234725076-03d89edb-b3ba-4629-8e65-07fee0e04c26.png)
![Image](https://user-images.githubusercontent.com/13149096/234725089-c18679bc-78d4-4c55-9239-4cb508b6cf73.png)
![Image](https://user-images.githubusercontent.com/13149096/234725099-1c57d117-5da8-4598-98ca-728ac310a9a8.png)

**Comment by kwindrem** [comment]
“ExtTransferSwitch” NOT “ExtTransferSwitchGitHib”
User is kwindrem
Branch is latest

**Comment by Lowbank** [comment]
My Bad sorry all installed thank you.
