### ISSUE TITLE
Generator warmup and cool down not functioning properly on 3.00~37

### ISSUE THREAD

**Issue by drtinaz** [kwindrem/ExtTransferSwitch#5]
Kevin, as requested posting this issue here. 
Venus beta 3.00~37 adds generator warmup and cool down settings, which seems not to work with the exttransferswitch mod.

I'd like to make a suggestion if that's alright. I don't know how these features are coded but it would be ideal I think if the ignore ac input happened before the generator actually started.

**Comment by kwindrem** [comment]
I think I know what the problem is. Warm-up and cool-down only occur if the current source is generator. Since ExtTransferSwitch is changing the input from grid/shore to generator and back, this will cause warm-up or cool-down periods to be skipped. Working on a solution.

**Comment by mpvader** [comment]
Hey @kwindrem , thanks for your help. One heads up: there is some possible improvement work going to happen from our side:

https://github.com/victronenergy/venus/issues/1067

**Comment by kwindrem** [comment]
Thanks for the heads up. I’ll keep an eye out for more changes.
—
Kevin

**Comment by kwindrem** [comment]
I have just posted GuiMods v7.43 that enhances the warm-up and cool-down logic to work with ExtTansferSwitch.

There is also a new version of ExtTransferSwitch (v2.6) that incorporates the same generator logic in case someone wants to run ExtTransferSwitch without GuiMods.

You still need ExtTransferSwitch installed to manage the external transfer switch even if you use GuiMods.

The change:
1) run through the warm-up period regardless of the state of the input type

2) keep track of generator loading and extend the cool-down period while the generator has the Multi's load.

3) cool-down until the cool-down period is satisfied, again without regard to the AC input.

4) monitor the "is on generator" AC input type continuously so it can shed load when on generator during warm-up or shut-down, and restore load when not on generator or when stopped or running.

**Comment by kwindrem** [comment]
I now have startstop.py working with ExtTransferSwitch

I have just posted GuiMods v7.43 that enhances the warm-up and cool-down logic to work with ExtTansferSwitch.

There is also a new version of ExtTransferSwitch (v2.6) that incorporates the same generator logic in case someone wants to run ExtTransferSwitch without GuiMods.

You still need ExtTransferSwitch installed to manage the external transfer switch even if you use GuiMods.

The change:

1. run through the warm-up period regardless of the state of the input type
2. keep track of generator loading and extend the cool-down period while the generator has the Multi's load.
3. cool-down until the cool-down period is satisfied, again without regard to the AC input.
4. monitor the "is on generator" AC input type continuously so it can shed load when on generator during warm-up or shut-down, and restore load when not on generator or when stopped or running.

The code is available here:

https://github.com/kwindrem/ExtTransferSwitch/blob/main/FileSets/v3.00~37/startstop.py

Or let me know and I'll do a pull request in dubs-generator and incorporate the changes in Victron code.

**Comment by drtinaz** [comment]
Kevin, the issue seems to have reappeared. I have also opened an issue in guimods since it seems to affect both mods. I am currently on Venus release v3.00 (cerbo gx). With exttransferswitch installed the warm up/cool down timers are broken. Full system reboot does not fix the issue. Uninstall exttransferswitch and timers are functional again. Exttransferswitch is v2.13.

Another problem I have discovered which may or may not be related (I will not open another issue on the matter since I don't know if it's possibly just related to this one).
After installing exttransferswitch, the gui restart does not seem to be enough to actually enable the exttransferswitch function. What I mean is that the digital inputs will change states properly, but the ac input type in system settings does not change back and forth between shore and generator when the digital inputs is toggled. (Yes, I have followed the setup procedure, digital input on grid and set system ac input to grid...toggle digital input to generator and set system ac input to generator) A full system reboot is required. Once the full reboot is completed, then the ac input will follow the digital inputs state properly (without any further configuration, the settings made before the reboot are now in effect).

**Comment by kwindrem** [comment]
I found a couple of issues, one that prevented the cool-down from happening. Another issue was the running status was not always updated. I think this was only in v3.00 beta versions. v3.15 is available. These changes are also in GuiMods v7.66

I did not find a problem with warm-up however. 

Also found an issue in ExtTransferSwitch when reinstalling. An update to SetupHelper (now v4.42) fixed that.
