### ISSUE TITLE
cool down timer question

### ISSUE THREAD

**Issue by drtinaz** [kwindrem/ExtTransferSwitch#7]
Kevin, not sure if this is in your ballpark or if this needs to be addressed with victron. I am using guimods and exttransferswitch both. The warmup/cooldown timers seem to function properly, but I do see an issue. With my generator, it takes about 2 seconds from the time the cerbo generator control relay is opened until the generator actually shuts down. I have monitored dbus during this process and it appears that the ignore ac input flag is reset instantly when the generator relay is opened, resulting in the ac input reconnecting to the generator output at the same time the generator is shutting down. This is not good. Would it be possible to add say a 5 second delay before setting the ignore ac input flag back to 0? Can you confirm your system functions the same way?

**Comment by kwindrem** [comment]
This exact issue was the subject of a recent issue posted to the Victron GitHub area. They will probably come up with a fix soon.

I will add a post-cooldown delay now until Victron makes an official change.

**Comment by kwindrem** [comment]
A new version of ExtTransferSwitch and GuiMods are up now that add a 30 second delay after cool-down ends before restoring AC input.

Note: Victron is also jumping on this and will most likely have a new version out very soon.
